apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-users-binding
subjects:
  - kind: User
    name: Ralf
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Pranav
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Andreas
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Felix
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Daniel
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Shebi
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Eduard
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Niranjan
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Alexander
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Oliver
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
