apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customresourcedefinition-manager
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["bitnami.com"]
    resources: ["sealedsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["lvm.topolvm.io"]
    resources: ["lvmclusters"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
