apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-customizations
spec:
  project: default
  source:
    path: sno/applications/maxds-vms/manifests
    repoURL: https://github.com/maxisses/openshift-virt-config.git
    targetRevision: main
  destination:
    namespace: maxds-vms
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
